lgb_params: 
  bagging_fraction: 0.849285747554019
  bagging_freq: 5
  bagging_seed: 0
  boosting_type: 'gbdt'
  data_random_seed: 0
  drop_seed: 0
  feature_fraction: 0.8212766928844304
  feature_fraction_seed: 0
  lambda_l1: 0.8955546599539566
  lambda_l2: 1.4423261095989717
  learning_rate: 0.03
  max_bin: 255
  max_depth': 43
  metric: 'auc'
  min_data_in_leaf: 149
  min_sum_hessian_in_leaf: 1.804477623298885
  num_leaves: 363
  objective: 'binary'
  seed: 0
  verbose: -1
n_repeats: 2
n_splits: 5
num_boost: 9999
early_stopping: 50
col_target: 'TARGET'
col_client: 'id_client'
cv_byclient: True
cols_exclude: ['id_client', 'target_adversarial', 'SIGN_DATE','SIGN_DATE_mon','TARGET','DATEFIRSTREG','TAXREG_REGDATE','SIGN_DATE','TAXREGPAY_REGDATE','BIRTHDATE']
cols_cat: ['OKTMO_CODE_lvl1','OKTMO_CODE_lvl2','OKFS_GROUP','OKOPF_GROUP','OKOGU_GROUP','OKATO_REGIONCODE', 'OKATO_FED', 'OKVED_CODE_lvl1','OKVED_CODE_lvl2','OKVED_CODE_lvl3', 'OKTMO_FED', 'OKTMO_CODE', 'OKVED_CODE', 'SEX_NAME', 'CITIZENSHIP_NAME']

adversarial_frac: 0.25
col_date: 'SIGN_DATE'
col_date_mon: 'SIGN_DATE_mon'
col_adversarial: 'target_adversarial'

hyperopt_trials: 3

